chill_activity_activityreasoncategory:
    path:     /{_locale}/admin/activityreasoncategory/
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:index" }

chill_activity_activityreasoncategory_show:
    path:     /{_locale}/admin/activityreasoncategory/{id}/show
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:show" }

chill_activity_activityreasoncategory_new:
    path:     /{_locale}/admin/activityreasoncategory/new
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:new" }

chill_activity_activityreasoncategory_create:
    path:     /{_locale}/admin/activityreasoncategory/create
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:create" }
    methods:  POST

chill_activity_activityreasoncategory_edit:
    path:     /{_locale}/admin/activityreasoncategory/{id}/edit
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:edit" }

chill_activity_activityreasoncategory_update:
    path:     /{_locale}/admin/activityreasoncategory/{id}/update
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:update" }
    methods:  [POST, PUT]

chill_activity_activityreasoncategory_delete:
    path:     /{_locale}/admin/activityreasoncategory/{id}/delete
    defaults: { _controller: "ChillActivityBundle:ActivityReasonCategory:delete" }
    methods:  [POST, DELETE]
