activitytype:
    path:     /{_locale}/admin/activitytype/
    defaults: { _controller: "ChillActivityBundle:ActivityType:index" }

chill_activity_activitytype_show:
    path:     /{_locale}/admin/activitytype/{id}/show
    defaults: { _controller: "ChillActivityBundle:ActivityType:show" }

chill_activity_activitytype_new:
    path:     /{_locale}/admin/activitytype/new
    defaults: { _controller: "ChillActivityBundle:ActivityType:new" }

chill_activity_activitytype_create:
    path:     /{_locale}/admin/activitytype/create
    defaults: { _controller: "ChillActivityBundle:ActivityType:create" }
    methods:  POST

chill_activity_activitytype_edit:
    path:     /{_locale}/admin/activitytype/{id}/edit
    defaults: { _controller: "ChillActivityBundle:ActivityType:edit" }

chill_activity_activitytype_update:
    path:     /{_locale}/admin/activitytype/{id}/update
    defaults: { _controller: "ChillActivityBundle:ActivityType:update" }
    methods:  [POST, PUT]

chill_activity_activitytype_delete:
    path:     /{_locale}/admin/activitytype/{id}/delete
    defaults: { _controller: "ChillActivityBundle:ActivityType:delete" }
    methods:  [POST, DELETE]
