chill_activity_activityreason:
    path:     /{_locale}/admin/activityreason/
    defaults: { _controller: "ChillActivityBundle:ActivityReason:index" }
    options:
        menus:
            admin: 
                order: 2000
                label: "Activity Reasons"

chill_activity_activityreason_show:
    path:     /{_locale}/admin/activityreason/{id}/show
    defaults: { _controller: "ChillActivityBundle:ActivityReason:show" }

chill_activity_activityreason_new:
    path:     /{_locale}/admin/activityreason/new
    defaults: { _controller: "ChillActivityBundle:ActivityReason:new" }

chill_activity_activityreason_create:
    path:     /{_locale}/admin/activityreason/create
    defaults: { _controller: "ChillActivityBundle:ActivityReason:create" }
    methods:  POST

chill_activity_activityreason_edit:
    path:     /{_locale}/admin/activityreason/{id}/edit
    defaults: { _controller: "ChillActivityBundle:ActivityReason:edit" }

chill_activity_activityreason_update:
    path:     /{_locale}/admin/activityreason/{id}/update
    defaults: { _controller: "ChillActivityBundle:ActivityReason:update" }
    methods:  [POST, PUT]

chill_activity_activityreason_delete:
    path:     /{_locale}/admin/activityreason/{id}/delete
    defaults: { _controller: "ChillActivityBundle:ActivityReason:delete" }
    methods:  [POST, DELETE]
